# Generated by Django 4.1.4 on 2022-12-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printmodeltag',
            name='print_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='printmodels.printmodel'),
        ),
        migrations.AddField(
            model_name='printmodeltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_models', to='printmodels.tag'),
        ),
        migrations.AddField(
            model_name='printmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='printmodels.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_models',
            field=models.ManyToManyField(related_name='orders', to='printmodels.printmodel'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadablefile',
            name='print_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadable_files', to='printmodels.printmodel'),
        ),
        migrations.AddField(
            model_name='category',
            name='print_models',
            field=models.ManyToManyField(related_name='categories', to='printmodels.printmodel'),
        ),
    ]
